theme = "PaperMod"
baseURL = "https://north-river1015.github.io/Minerva/"
languageCode = 'en-us'
title = 'Minerva'
#右下のNextボタンを消したい。
pagination.pagerSize = 2000


# for search function
[outputs]
    home = ["HTML", "RSS", "JSON"]
# for search function

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Search"
    url = "/search"
    weight = 5 


[[menu.main]]
    name = "公約の判定基準"
    url = "/rubric"
    weight = 10

[[menu.main]]
    name = "ミスの報告"
    url = "https://forms.gle/kGAFfXspVisRCNRVA"
    weight = 16

[[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# 地図をウェブサイトに入れるために、[markup.goldmark.renderer]　unsafeをtrueに変更
[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.footnote]
        backlinkHTML = '&#x21a9;&#xfe0e;'
        enable = true
        enableAutoIDPrefix = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoDefinitionTermID = false
      autoHeadingID = true
      autoIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = "never"
      [markup.goldmark.renderHooks.link]
        useEmbedded = "never"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'